pipeline {
    agent any

    environment {
        REMOTE_HOST = '192.168.2.142'
        REMOTE_USER = 'iman'
        INDEX_URL = 'https://raw.githubusercontent.com/ihrahimi/DevOps/main/jenkins/nginx-simple/index.html'
        IMAGE_NAME = 'custom-nginx'
    }

    stages {
      
        stage('Download Updated index.html') {
            steps {
                sh 'curl -o index.html ${INDEX_URL}'
            }
        }

        stage('Send to Remote Builder') {
            steps {
                // Send index.html to remote server
                sh """
                scp index.html ${REMOTE_USER}@${REMOTE_HOST}:/home/${REMOTE_USER}/index.html
                """
            }
        }

        stage('Build Docker Image on Remote') {
            steps {
                // SSH into remote and build Docker image
                sh """
                ssh ${REMOTE_USER}@${REMOTE_HOST} '
                mkdir -p ~/nginx-build &&
                mv ~/index.html ~/nginx-build/index.html &&
                echo "FROM nginx:latest \nCOPY index.html /usr/share/nginx/html/index.html " > ~/nginx-build/Dockerfile 
                cd ~/nginx-build &&
                docker container stop ${IMAGE_NAME}
                docker container prune -f
                docker image prune -f
                docker build -t ${IMAGE_NAME} .
                docker container run -d -p 8000:80 --name ${IMAGE_NAME} ${IMAGE_NAME}
                '
                """
            }
        }
    }

    post {
        success {
            echo '✅ Docker image built successfully on remote server!'
        }
        failure {
            echo '❌ Pipeline failed.'
        }
    }
}
