- name: Install tmux
  hosts: all
  become: true
  tasks:
    - name: Ensure tmux is installed
      apt:
        name: tmux
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure tmux is installed (RedHat-based)
      yum:
        name: tmux
        state: present
      when: ansible_os_family == "RedHat"
