kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  # Control-plane (master) node
  - role: control-plane
#    image: kindest/node:v1.27.3  # Adjust version as needed

  # Worker 1: Exposes host port 8080 → container port 8080
  - role: worker
 #   image: kindest/node:v1.27.3
    extraPortMappings:
      - containerPort: 30000
        hostPort: 8080
        listenAddress: "0.0.0.0"  # Bind to all host interfaces
        protocol: TCP
    extraMounts:
    # Mount host's /srv directory to /srv in the worker node
      - hostPath: "/srv"
        containerPath: "/srv"
        # readOnly: false makes it writable (default)
        propagation: Bidirectional  # For better file sync between host and container

  # Worker 2: Exposes host port 9080 → container port 8080
  - role: worker
  #  image: kindest/node:v1.27.3
    extraPortMappings:
      - containerPort: 30000
        hostPort: 9080
        listenAddress: "0.0.0.0"
        protocol: TCP
    extraMounts:
    # Mount host's /srv directory to /srv in the worker node
      - hostPath: "/srv"
        containerPath: "/srv"
        # readOnly: false makes it writable (default)
        propagation: Bidirectional  # For better file sync between host and container

  # Worker 3: Exposes host port 10080 → container port 8080
  - role: worker
   # image: kindest/node:v1.27.3
    extraPortMappings:
      - containerPort: 30000
        hostPort: 7080
        listenAddress: "0.0.0.0"
        protocol: TCP
    extraMounts:
    # Mount host's /srv directory to /srv in the worker node
      - hostPath: "/srv"
        containerPath: "/srv"
        # readOnly: false makes it writable (default)
        propagation: Bidirectional  # For better file sync between host and containe
