#nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: website-storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: website-storage
        persistentVolumeClaim:
          claimName: website-pvc  # Use our PVC
