apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-deployment
  labels:
    app: nfs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nfs-app
  template:
    metadata:
      labels:
        app: nfs-app
    spec:
      containers:
      - name: nfs-container
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nfs-volume
          mountPath: "/usr/share/nginx/html"
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: nfs-pvc

