apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort  # Explicitly set NodePort type
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000  # Fixed NodePort (30000-32767 range)
