apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: my-app-pdb
  namespace: default
spec:
  minAvailable: 2  # Ensures at least 2 pods remain available during disruptions
  selector:
    matchLabels:
      app: my-app  # Must match the labels of your pods
