apiVersion: settings.k8s.io/v1alpha1
kind: PodPreset
metadata:
  name: volume-mount-preset
spec:
  selector:
    matchLabels:
      demo: "true"
  volumeMounts:
  - name: demo-volume
    mountPath: /data
  volumes:
  - name: demo-volume
    emptyDir: {}
